apiVersion: v1
kind: Pod
metadata:
        name: my-deployment
        labels:
                name: myapp
                type: fornt-end
spec:
     containers:
             - name: nginx
               image: nginx
               ports:
               - containerPort: 80 
